# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
before_install:
  - sudo apt-get -qq install gcc
sudo: false
cache: packages

notifications:
  email:
    recipients:
      - maximilian.hesselbarth@uni-goettingen.de
    on_success: change # default: change
    on_failure: change # default: always
