# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

deprecated_rcpp_random_distance <- function(n, species, n_proposed = 1000000L, max_dist = 80) {
    .Call('_rabmp_deprecated_rcpp_random_distance', PACKAGE = 'rabmp', n, species, n_proposed, max_dist)
}

deprecated_rcpp_create_seedlings <- function(coords, number, species) {
    .Call('_rabmp_deprecated_rcpp_create_seedlings', PACKAGE = 'rabmp', coords, number, species)
}

rcpp_calculate_ci <- function(matrix, alpha, beta, max_dist) {
    .Call('_rabmp_rcpp_calculate_ci', PACKAGE = 'rabmp', matrix, alpha, beta, max_dist)
}

rcpp_calculate_distance <- function(current_x, current_y, other_x, other_y) {
    .Call('_rabmp_rcpp_calculate_distance', PACKAGE = 'rabmp', current_x, current_y, other_x, other_y)
}

rcpp_calculate_ci_sugar <- function(matrix, alpha, beta, max_dist) {
    .Call('_rabmp_rcpp_calculate_ci_sugar', PACKAGE = 'rabmp', matrix, alpha, beta, max_dist)
}

rcpp_calculate_mortality_probs <- function(species, dbh) {
    .Call('_rabmp_rcpp_calculate_mortality_probs', PACKAGE = 'rabmp', species, dbh)
}

rcpp_calculate_probability <- function(beta, theta, max_dist) {
    .Call('_rabmp_rcpp_calculate_probability', PACKAGE = 'rabmp', beta, theta, max_dist)
}

rcpp_create_seedlings <- function(coords, number, species) {
    .Call('_rabmp_rcpp_create_seedlings', PACKAGE = 'rabmp', coords, number, species)
}

rcpp_random_distance <- function(number_seeds, species, max_dist) {
    .Call('_rabmp_rcpp_random_distance', PACKAGE = 'rabmp', number_seeds, species, max_dist)
}

