# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_calculate_ci <- function(matrix, alpha, beta, max_dist) {
    .Call('_rabmp_rcpp_calculate_ci', PACKAGE = 'rabmp', matrix, alpha, beta, max_dist)
}

rcpp_calculate_distance_probability <- function(beta, theta, max_dist) {
    .Call('_rabmp_rcpp_calculate_distance_probability', PACKAGE = 'rabmp', beta, theta, max_dist)
}

rcpp_calculate_mortality_probs <- function(species, dbh, int_beech_early, dbh_beech_early, int_beech_late, dbh_beech_late, dinc_beech, int_ash, dbh_ash, int_others, dbh_others) {
    .Call('_rabmp_rcpp_calculate_mortality_probs', PACKAGE = 'rabmp', species, dbh, int_beech_early, dbh_beech_early, int_beech_late, dbh_beech_late, dinc_beech, int_ash, dbh_ash, int_others, dbh_others)
}

rcpp_calculate_number_seeds <- function(species, dbh, str_beech, str_ash, str_sycamore, str_hornbeam, str_others) {
    .Call('_rabmp_rcpp_calculate_number_seeds', PACKAGE = 'rabmp', species, dbh, str_beech, str_ash, str_sycamore, str_hornbeam, str_others)
}

rcpp_create_seedlings <- function(coords, number, species) {
    .Call('_rabmp_rcpp_create_seedlings', PACKAGE = 'rabmp', coords, number, species)
}

rcpp_random_distance <- function(number_seeds, species, max_dist) {
    .Call('_rabmp_rcpp_random_distance', PACKAGE = 'rabmp', number_seeds, species, max_dist)
}

