# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_calculate_ci <- function(matrix, max_dist, alpha, beta) {
    .Call('_rabmp_rcpp_calculate_ci', PACKAGE = 'rabmp', matrix, max_dist, alpha, beta)
}

